export const BdModels = {
    itens : {
        id:"number",
        category:"text",
        type:"text",
        name: "text",
        atk:"number",
        atks:"number",
        def:"number",
        hp:"number",
        crit_chance:"number",
        crit_mult:"number"
    },
    builds:{
        id:"number",
        id_account:"number",
        name:"text",
        helmet:"number",
        body:"number",
        gloves:"number",
        boots:"number",
        main_hand:"number",
        off_hand:"number",
        amulet:"number",
        ring:"number",
        belt:"number"
    },
    accounts:{
        id:"number",
        name:"text",
        email:"text"
    },
    monsters:{
        id:"number",
        type:"text",
        name:"text",
        atk:"number",
        atks:"number",
        def:"number",
        hp:"number",
        crit_chance:"number",
        crit_mult:"number"
    }
};