export const BdModelsList = {
    itens:[
        "id",
        "category",
        "type",
        "name",
        "atk",
        "atks",
        "def",
        "hp",
        "crit_chance",
        "crit_mult"
    ],
    builds:[
        "id",
        "id_account",
        "name",
        "helmet",
        "body",
        "gloves",
        "boots",
        "main_hand",
        "off_hand",
        "amulet",
        "ring",
        "belt"
    ],
    accounts:[
        "id",
        "name",
        "email"
    ],
    monsters:[
        "id",
        "type",
        "name",
        "atk",
        "atks",
        "def",
        "hp",
        "crit_chance",
        "crit_mult"
    ]
};